topdir      := ../..
proj_env    := user
proj_target := lib
proj_proto  := \
	transaction.proto \
	value-db.proto \
	key-db.proto

proj_incl   := . $(topdir)/include/util
proto_ccp   := $(topdir)/app/protobuf

include $(topdir)/Makefile.incl
