topdir        := ../..
proj_env      := user
proj_target   := test

proj_cpp      := \
	bigint.cpp

# List of binaries to build
#
proj_exes     := \
	bigint

# Run binaries during unit test phase
#
proj_tests     := \
	bigint

proj_sys_libs  := \
	util

proj_foss_libs := \
	protobuf-3

proj_dep_libs  := \
	util

bigint         := bigint.cpp

# Arguments to run unit test code.
#
bigint_args    :=

include ../Makefile
