topdir         := ../..
proj_env       := user
proj_target    := test
proj_cpp       := \
	unit-test.cpp

proj_json      :=

proj_exes      := unit
proj_tests     := unit
unit           := unit-test.cpp

proj_sys_libs  :=
proj_foss_libs :=
proj_dep_libs  :=

# Arguments to run unit test code
#
unit_args      :=

include ../Makefile
