topdir      := ../..
proj_env    := user
proj_target := lib
proj_cc     := \
	bgzf.c \
	kmath.c \
	knhx.c \
	ksa.c \
	kstring.c \
	kthread.c \
	khmm.c \
	knetfile.c \
	kopen.c \
	kson.c \
	ksw.c \
	kurl.c

proj_libs  := klib
klib       := $(proj_cc)

#proj_exes  := kmath knetfile knhx kopen kson kstring ksw kurl
#kmath      := kmath.c
#knetfile   := knetfile.c
#knlx       := knlx.c
#kopen      := kopen
#kson       := kson.c
#ksw        := ksw.c
#kurl       := kurl.c

include $(topdir)/Makefile.incl
