<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<div class='row content' style='overflow:auto; max-height: 80vh; font-size:16px'>
  <p>Có rất nhiều website viết về nhiều vấn nạn tại Việt Nam...</p>
  <p>Có rất nhiều người miệt mài tâm huyết viết nhiều về chủ đề khai phóng, các giá trị của quyền tự do…</p>
  <p>Bởi lẽ, khá đông người Việt còn quan tâm đến vận mệnh của đất nước vì nhiều lý do khác nhau...</p>
  <p>Khắc sâu trong tâm khảm, hầu hết người Việt đều có một ước mơ chung về tương lai đất nước Việt Nam tươi đẹp hơn, xã hội nhân bản hơn, quốc gia hùng mạnh hơn...</p>
  <br/>
  <p>Là dân kỹ thuật, tôi nhìn thấy nhiều cơ hội để mọi người cùng chung một ước mơ có thể gắn kết lại với nhau, cùng hợp lực với nhau, cùng biến giấc mơ Việt thành hiện thực.  Không bàn đến chuyện chính trị xa vời, lý tưởng cao siêu, tôi nhận thấy người Việt có nhiều cơ hội để giải quyết mấu chốt quan trọng nhất của các vấn nạn hiện tại, đó là bài toán kinh tế.  Giả sử rằng khi những người đang ở Việt Nam dám thách thức với tù đày đứng thẳng hành động cho ước mơ của mình mà được hoàn toàn độc lập về kinh tế, có được sức mạnh về tài chính, họ sẽ làm được nhiều việc hiệu quả hơn, thiết thực hơn; họ sẽ có phương tiện đắc lực hơn để thực hiện những gì họ mong muốn.  Không phải chuyện đóng góp gây quỹ ủng hộ cá nhân này, hội đoàn nọ, tôi muốn đề cập đến sức mạnh kinh tế của người Việt Nam.  Điểm quan trọng nhất ở đây là, một khi nhiều người Việt nhận thức được sức mạnh kinh tế của bản thân mình, con đường từ giấc mơ Việt đến hiện thực sẽ trở thành khả thi và rút ngắn hơn rất nhiều.</p>
  <br/>
  <p>Cuộc cách mạng Internet đã và đang làm thay đổi tận gốc xã hội toàn cầu.  Đối mặt với những bất ổn do nó mang lại là nhiều cơ hội đã được chứng minh qua sự thành công vượt bậc của các công ty mới thành lập chưa đến 10 năm tuổi.  Chấn động mạnh nhất của Internet là ở hai lĩnh vực truyền thông và mua bán lẻ (media, retail).  Trong nghành truyền thông, báo giấy đã bị thay thế bằng tin tức trên mạng; thay vào một đội ngũ biên tập chuyên nghiệp, phóng viên đông đảo là từng người ở đời thường nghiệp dư với chiếc điện thoại thông minh nhỏ bé và đường truyền lên mạng Internet.  Trong nghành buôn bán lẻ, thay vào những tiệm bán với kho bãi, hàng hoá, quầy bán, người làm, là những tiệm trực tuyến (online), với những khái niệm mới lạ như dropshipping, affiliation…  Những sự thay đổi đó và sức mạnh kinh tế của người Việt Nam có gì liên quan đến nhau?</p>
  <br/>
  <p>Thực tế thành công của các công ty Internet đã chứng minh rằng mỏ vàng của nền kinh tế điện số không phải là quý kim, hiện vật, công cụ, mà là dữ liệu, thông tin, kiến thức.  Người ta còn ước tính rằng một chiếc xe tự lái sau 5 năm, giá trị dữ liệu thu thập được còn đắt tiền hơn cả bản thân chiếc xe ấy.  Với máy móc tự động, giá năng lượng rẻ, nguồn tài nguyên đa dạng, giá thành một sản phẩm chỉ còn giữ phần trăm rất nhỏ so với chi phí tiếp thị đến tận tay người tiêu dùng.  Đó là chưa kể đến phần dịch vụ của nền kinh tế tri thức, hiểu nôm na là may một chiếc áo không còn là vấn đề lớn; thiết kế mẫu thời trang hợp gu khách hàng mới là giá trị gia tăng vượt bậc của dịch vụ thiết kế.  Giá trị của khối cơ sở dữ liệu của bất kỳ công ty Internet nào đều lớn hơn cơ sở vật chất, vốn tư bản của họ gấp bội lần.  Như vậy người Việt có khối dữ liệu nào, thông tin gì, kiến thức ra sao để được gọi là sức mạnh kinh tế?</p>
  <br/>
  <p>Các công ty truyền thông có sức mạnh được coi như là quyền lực nhánh thứ tư của chính quyền nước Mỹ.  Trong thời đại Internet, một công ty truyền thông mới không tên tuổi là Breitbart Network đã đóng vai trò không nhỏ trong việc vận động cử tri bỏ phiếu cho đảng CH, giám đốc của công ty ấy đang là cố vấn thân cận của TT Trump.  Trong khi đó, các công ty truyền thông lớn hồi nào đến giờ hiện nay chưa có cách nào để thiết lập lại ưu thế thống trị của họ so với trước thời kỳ Internet.  Sức mạnh truyền thông của cộng đồng người Việt dùng Facebook là một bằng chứng rõ ràng về điều này.  Nhờ có Facebook mà cộng đồng đấu tranh đòi dân chủ cho Việt Nam không còn cô đơn như trước nữa.</p>
  <br/>
  <p>Ngày nay ở Mỹ, các tập đoàn buôn bán lẻ (retail) đang gặp khó khăn cạnh tranh với thương mại trực tuyến.  Nhiều tập đoàn lâu đời nay gặp nguy cơ phá sản, phải đóng cửa nhiều tiệm.  Các thương xá lớn (mall) nay chỉ còn là khung sườn của dĩ vãng hoành tráng, một thời là chốn sinh hoạt của thanh niên mới lớn ở Mỹ, một phần là nét văn hoá của nước Mỹ.  Thế nhưng nước Mỹ là nơi của sự phá hoại sáng tạo (creative destruction), trật tự cũ luôn bị kỹ thuật mới dẹp bỏ, mở ra nhiều cơ hội cho một nền trật tự mới mang đến lợi ích cho nhiều người hơn.  Dù rằng có nhiều công ty đi trước đã thành công vượt bậc trong nền công nghệ hiện tại, lịch sử nước Mỹ cho thấy về đường dài, yếu tố thành công tuỳ thuộc vào nhiều yếu tố khác nhau.  Số lượng các công ty đi tiên phong trong lĩnh vực mới được tiếp tục giữ vững thị phần của họ sau thời gian dài chỉ đếm được trên đầu ngón tay.  Như vậy khối cộng đồng người Việt có lợi thế gì trong bối cảnh của nền trật tự mới này trong lĩnh vực buôn bán lẻ?</p>
  <br/>
  <p>“Đông người lập thành chợ", đó là gốc rễ của nền kinh tế Việt Nam từ xưa đến nay.  Một cái chợ tự phát là trung tâm kinh tế của mọi làng xã, mọi góc ngõ của thị thành Việt Nam, là nơi nuôi sống bao gia đình Việt Nam xuyên suốt từng thời kỳ thăng trầm lịch sử.  Tuy có đông người Việt trên Internet, nhưng nhiều rào cản khó vượt qua đã ngăn cản sự hình thành của các chợ tự phát trong cộng đồng người Việt.  Nếu giả sử rằng mọi rào cản không còn nữa, khi mọi người Việt Nam bất luận trong hay ngoài nước đều có khả năng buôn bán với nhau dễ dàng, đó sẽ là sức mạnh kinh tế đủ sức biến giấc mơ Việt thành hiện thực và sẽ còn đi xa hơn nữa.  Từ đó, để hình thành một thế lực có đủ sức mạnh xoay chuyển Việt Nam ra ngoài vòng kim cô Cộng Sản và thoát khỏi quỹ đạo Trung Quốc sẽ không còn là tương lai xa vời nữa.</p>
  <br/>
  <p>Trở về với thực tế hiện tại, muốn lập chợ phải có đủ 4 yếu tố chính là: có hàng để bán, có cách giao hàng cho khách, có phương tiện thanh khoản, và có đám đông để lập chợ.  Tôi sẽ cố gắng tóm lược những yếu tố đó trong bài này để các bạn thấy được sức mạnh của mỗi người chúng ta.</p>
  <br/>
  <p>Tôi chắc rằng một khi dễ lập chợ và trao đổi an toàn, người trong nước sẽ giới thiệu nhiều món cổ truyền từ thuốc Nam, đến đặc sản địa phương, đến các mặt hàng thủ công nghiệp truyền thống...  Thế nnhưng, hàng hoá để bán không chỉ đơn giản gói gọn vào những gì trong nước có, hải ngoại cần và ngược lại.  Hiện đang có khái niệm mới cho phép mọi người bất kể ở đâu có thể bán hàng ở bất cứ nơi nào mà không cần phải sản xuất, tiếng Anh gọi là dropshipping.  Tại sao lại có chuyện lạ đời như vậy, nó có phải là dạng lừa đảo kiểu bán hàng “đa cấp" hay không?</p>
  <br/>
  <p>Ở các nước giàu, giá sản xuất của một sản phẩm chỉ là phần trăm nhỏ so với giá thành mà người tiêu dùng phải trả.  Phần lớn đội giá là ở chi phí cho quảng cáo, tiếp thị, và thương hiệu.  Một sản phẩm cùng nhà sản xuất nếu đóng thương hiệu nổi tiếng như Taylorswift sẽ đắt tiền gấp bội hơn những thương hiệu khác.  Tương tự như các tờ báo lớn bị Internet làm lao đao trước các mạng không tên tuổi như Breitbart, hay lu mờ trước các mạng xã hội như Facebook, dropshipping là cách mà cá nhân không tên tuổi có cơ hội xây dựng thương hiệu cho chính mình, thay vì phải chờ được nổi tiếng như Taylorswift.  Đối với nhà sản xuất, nếu bạn tiếp thị được cho họ, họ kiểm soát được phần lời của họ, phần lời còn lại do bạn bán được là lợi nhuận của riêng bạn.  Công bình cho cả hai bên.  Người mua cũng có lợi nếu họ không ham thương hiệu nổi tiếng.</p>
  <br/>
  <p>Vấn đề khó kế tiếp là làm sao xây dựng thương hiệu cho chính mình?  Người Việt rất khó duy trì được các hoạt động gây quỹ lâu dài, nhưng không phải vì thế mà nhiều người không gây được nguồn kinh phí hoạt động.  Cộng đồng Facebook cũng không ít người viết lên suy nghĩ của họ, được hàng ngàn người theo dõi, kết bạn.  Với dropshipping, họ có thể dùng lợi thế ấy để xây dựng được thương hiệu cho họ, cho nhóm của họ, gây quỹ hoạt động từ lợi nhuận do họ làm ra.  Người mua thay vì mua cùng sản phẩm, trả cùng giá thành từ chỗ khác, mua từ thương hiệu mà họ muốn ủng hộ sẽ đặt đồng tiền của họ vào đúng người, đúng chổ.  Thêm vào đó, lợi nhuận mà những người muốn gây quỹ là hoàn toàn thuộc về họ, nhóm của họ.  Họ được toàn quyền sử dụng mà không cần phải bị áp lực từ bên ngoài xăm xoi như khi họ kêu gọi đóng góp gây quỹ.  Khi người mua bỏ phiếu bằng đồng tiền của họ, thương hiệu yếu kém vì nhiều lý do chính đáng sẽ không còn chổ đứng trên thị trường.</p>
  <br/>
  <p>Các bạn nên google để tìm hiểu thêm về dropshipping.  Đằng sau nỗi ảm đảm của các thương xá ở Mỹ là sự phát triển âm thầm ở bên trong từ các nhà sản xuất, các công ty vận tải chuẩn bị cho trật tự mới này.  Bạn có thể đóng thương hiệu cho mình, tiếp thị sản phẩm trên mạng, đơn đặt hàng cùng với tiền của người mua gởi đến nhà sản xuất.  Họ sẽ gởi hàng hoá thằng đến người tiêu dùng, và họ trả tiền lợi nhuận lại cho bạn.  Họ không cần biết bạn ở đâu, chỉ cần bạn bán hàng được cho họ và bạn có cách cho họ trả tiền là họ mãn nguyện; bởi lẽ, kỹ thuật tự động hoá hiện đại cho phép họ bán lẻ và gởi thẳng đến tay từng khách hàng, thay vì phải dựa vào kênh phân phối bán sỉ như truyền thống.</p>
  <br/>
  <p>Hai yếu tố quan trọng còn lại là phương tiện thanh khoản và đám đông để lập chợ.  Đó là mấu chốt vấn đề trong dự án tôi muốn giới thiệu đến các bạn.  Hiện tại, chỉ có mình tôi đang phát triển dự án này.  Tìm được người giỏi về kỹ thuật đồng hành để làm dự án nặng về chính trị này là điều vô cùng khó.  Website này là phần đầu của dự án này, mục đích là thu hút đám đông để lập chợ.  Chuẩn bị cho giai đoạn kế là giới thiệu phương tiện thanh khoản cho mọi người Việt toàn cầu cùng liên kết với các nhà sản xuất để mọi người đều có thể tự kinh doanh bằng dropshipping.  Người ta dự đoán rằng trong tương lai, sản xuất theo nhu cầu của từng người sẽ thống trị đẩy lùi kiểu sản xuất đại trà như hiện tại.  Trong xu hướng đó, yếu tố "đông người lập chợ" lại càng quan trọng hơn nữa, thích hợp với kiểu giao dịch truyền thống của người Việt.</p>
  <br/>
  <p>Để thu hút đám đông, tôi cần sự giúp đỡ của các bạn, giúp tôi giới thiệu dự án này đến nhiều người.  Khi đã có đám đông quan tâm, tôi sẽ có cơ hội tìm được người cộng tác, cũng như tìm được nhà đầu tư tài trợ trong thế mạnh.  Trong thời gian phát triển dự án này, tôi sẽ cố gắng giữ đám đông, dành thì giờ chia xẻ kiến thức của mình, từ kỹ thuật đến kinh nghiệm học tiếng Anh, đến kinh tế, chính trị.  Tôi mở toàn bộ mã nguồn của dự án này với BSD license.  Dân kỹ thuật biết rõ về BSD, bạn được tự do sử dụng mã nguồn, chỉ cần bạn giữ tên tác giả là xong.</p>
  <br/>
  <p>“Con đường vạn dặm bắt đầu bằng những bước nhỏ".  Tôi đã đi những bước ban đầu cho dự án này.  Nó mất khá nhiều thời gian bởi vì làm web không phải là nghề ruột của tôi, phải vừa làm vừa tự học.  Có một câu tôi rất tâm đắc, đại khái là kỹ sư phần mềm ngày nay có khả năng giúp được cả triệu người nghèo, đừng ham làm giàu mà đeo đuổi những giải pháp không cần có cho người khá giả, khi bạn giúp được triệu người mà không cần phải trả công, một ngày nào đó sự thành công của bạn sẽ đến từ triệu người ấy.  Website này tuy còn nhiều việc phải làm nhưng tôi muốn giới thiệu rộng rãi để tìm người đồng hành, và bạn bè kiên nhẫn muốn đi cùng đến đích.  Nếu các bạn muốn đi cùng thì IM cho tôi, hoặc đăng ký account.  Nếu bạn muốn cộng tác kỹ thuật, tôi sẽ chia xẻ toàn bộ kinh nghiệm, kiến thức của mình cho bạn.  Rất mong các bạn đăng ký, sử dụng website này để chúng ta bắt đầu quây tụ một đám đông.  Có đám đông chúng ta sẽ có thông tin, kiến thức, chợ búa...  Đó là mỏ vàng không hề nhỏ, là sức mạnh không thể chia rẽ được.</p>

</div>
