topdir      := ../..
proj_env    := user
proj_target := lib
proj_cpp    := \
	lock.cpp \
	object.cpp \
	hash-obj.cpp \
	list-obj.cpp \
	lru-cache.cpp

proj_libs   := cpptype
cpptype     := $(proj_cpp)

include $(topdir)/Makefile.incl
