topdir       := ../../../../..

proj_clean   := $(wildcard *.dep)
proj_scripts := proj_css

proj_less    := \
	smartadmin-production.less \
	smartadmin-production-plugins.less

include ../../../Makefile.incl
