topdir      := ../..
proj_env    := user
proj_target := tool
proj_cpp    := \
	json2c++.cpp

proj_exes   := jsonc
jsonc       := json2c++.cpp

proj_foss_libs := \
	janson

proj_dep_libs  :=
proj_sys_libs  := \
	boost_thread \
	boost_system \
	boost_filesystem

include ../Makefile
