topdir      := ../..
proj_env    := user
proj_target := lib
proj_cpp    := \
	program.cpp \
	module.cpp \
	request.cpp \
	logger.cpp \
	exe-loop.cpp \
	fdrw.cpp \
	fsm.cpp \
	log.cpp

proj_libs  := di
di         := $(proj_cpp)

include $(topdir)/Makefile.incl
