topdir      := ../..
proj_env    := user
proj_target := lib
proj_cpp    := \
	json-obj.cpp \
	json-out.cpp \
	json-plugin.cpp \
	json-app.cpp

proj_libs   := json
json        := $(proj_cpp)

include $(topdir)/Makefile.incl
