topdir      := ../..
proj_env    := user
proj_target := lib
proj_cc     := \
	dlist.c \
	list.c \
	hash.c \
	bmap.c \
	data-statefsm.c \
	statefsm.c \
	unix-util.c \
	shm-slist.c \
	shm-dlist.c \
	shm-slab.c \
	uuid-map.c \
	debug.c \
	ctrlvec.c

proj_libs  := ctype
ctype      := $(proj_cc)

include $(topdir)/Makefile.incl
