topdir        := ../..
proj_env      := user
proj_target   := lib
proj_incl     := .
proj_cpp      :=

# Run binaries during unit test phase
#
proj_libs     := utest
utes          := $(proj_cpp)

include ../Makefile
